### ISSUE TITLE
Sitemap collects 'variants' nodes and add to the sitemap

### ISSUE THREAD

**Issue by serialcool** [magnolia-community/google-sitemap#1]
If you use page personalization the generated sitemap could contains links to the _variants_ page sub node. These links could not be rendered and result in a 404 http status code.

I think the bug is at this line https://github.com/magnolia-community/google-sitemap/blob/master/src/main/java/info/magnolia/module/googlesitemap/service/SiteMapService.java#L177

Instead of iterating over _mgnl:content_ it should be used _mgnl:page_.

**Comment by rgange** [comment]
I'm not sure. While the variants do live on a subnode of the page, the variants themselves are mgnl:page nodes. So I think this would be all pages who's parent is not mgnl:variants. That would be the correct filter.

**Comment by rgange** [comment]
Ok I verified that changing it to mgnl:page does work. I don't have any variants listed in the map.

**Comment by rgange** [comment]
https://github.com/magnolia-community/google-sitemap/commit/d88aa3ba71f57a421951413c29b8c94518dc8e6a

Update to 3.0.1
