### ISSUE TITLE
Google Sitemap not working with Magnolia 6.2.1

### ISSUE THREAD

**Issue by rgange** [magnolia-community/google-sitemap#2]
The "PropertyExistsDelegateTask" got replaced by Magnolia 6.2.1 but is still in use in the latest version of the Google Sitemap Module (5.1).

This causes the build / startup to fail.

Affected Release 6.1.5:

Deprecated Content API classes replaced
In the Site module, the PropertyExistsDelegateTask and PropertyValueDelegateTask classes of the legacy Content API have been replaced with HasPropertyDelegateTask and ValueOfPropertyDelegateTask respectively.

https://jira.magnolia-cms.com/browse/MGNLSITE-95

**Comment by tomtrapp** [comment]
+1
Blocks me currently

**Comment by rgange** [comment]
Ok, I will look at at it today. Hopefully it's a quick fix.

**Comment by rgange** [comment]
I released 3.1 just now. Thanks again!

**Comment by tomtrapp** [comment]
**That is simple awesome, thank you very much!**
